language: node_js
node_js:
  - '14'

branches:
  only:
    - master
    - main

env:
  global:
    - NODE_ENV=production
    - AWS_REGION=us-west-2
    - S3_BUCKET_NAME=my-react-app-bucket
    - CF_DISTRIBUTION_ID=my-cloudfront-distribution-id

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_success:
  - npm test
  - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
  - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths "/*"
